# Generated by Django 5.1.5 on 2025-02-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_category_name_ru_category_name_uz_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("PAYNET", "Paynet"), ("PAYME", "Payme")],
                default="PAYME",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.BooleanField(default=False, verbose_name="Payment Status"),
        ),
    ]
