# Generated by Django 5.1.5 on 2025-02-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_order_payment_method_order_payment_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="botusers",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Bot User",
                "verbose_name_plural": "Bot Users",
            },
        ),
        migrations.AlterField(
            model_name="botusers",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="botusers",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Full Name"
            ),
        ),
        migrations.AlterField(
            model_name="botusers",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="botusers",
            name="language_code",
            field=models.CharField(
                choices=[("uz", "Uzbek"), ("ru", "Russian")],
                default="uz",
                max_length=10,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="botusers",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Last Name"
            ),
        ),
        migrations.AlterField(
            model_name="botusers",
            name="phone",
            field=models.BigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="botusers",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("moderator", "Moderator"),
                    ("user", "User"),
                ],
                default="user",
                max_length=10,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="botusers",
            name="username",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Username"
            ),
        ),
    ]
