# Generated by Django 5.1.5 on 2025-02-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_botusers_options_alter_botusers_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=100, verbose_name="Amount"
            ),
        ),
    ]
