# Generated by Django 5.1.5 on 2025-02-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_cart_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=100,
                null=True,
                verbose_name="Amount",
            ),
        ),
    ]
