# Generated by Django 5.1.5 on 2025-02-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_cartitem_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[("DONATE", "Donate"), ("PRODUCT", "Product")],
                default="PRODUCT",
                max_length=20,
            ),
        ),
    ]
