# Generated by Django 5.1.5 on 2025-02-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_help"),
    ]

    operations = [
        migrations.AddField(
            model_name="info",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="info/", verbose_name="Image"
            ),
        ),
    ]
