# Generated by Django 5.1.5 on 2025-02-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_info_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("PAYNET", "Paynet"), ("PAYME", "Payme"), ("CLICK", "Click")],
                default="PAYME",
                max_length=100,
            ),
        ),
    ]
