# Generated by Django 5.1.5 on 2025-02-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_alter_order_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=100, null=True
            ),
        ),
    ]
